name: yumemi_codecheck
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_gen: ^5.12.0
  flutter_hooks: ^0.21.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_web_auth_2: ^4.1.0
  font_awesome_flutter: ^10.10.0
  freezed_annotation: ^3.0.0
  hooks_riverpod: ^2.6.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod_paging_utils: ^0.8.1

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0
  json_serializable: ^6.7.1
  riverpod_generator: ^2.6.1
  yumemi_lints: ^4.2.0

flutter:
  generate: true
  uses-material-design: true
  assets:
     - .env
