name: yumemi_codecheck
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod_paging_utils: ^0.7.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.6.1
  yumemi_lints: ^4.2.0

flutter:
  uses-material-design: true